# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Trang chủ
    url: /
    weight: 10
  - name: Truyện
    url: docs/
    weight: 20

sidebar:
  - identifier: more
    name: Links
    params:
      type: separator
    weight: 1
  - identifier: github
    name: "GitHub ↗"
    url: "https://github.com/tienthieusac/tienthieusac.github.io"
    weight: 2
  - identifier: facebook
    name: "Facebook ↗"
    url: "https://facebook.com/miti99"
    weight: 3
