# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Tiên Thiếu Sắc
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: deep purple
  language: vi
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
plugins:
#  - meta
  - offline
#  - optimize
  - search
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tienthieusac
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/miti99
  analytics:
    provider: google
    property: G-FSF7ZLXSZP
copyright: |
  Made by <a href="https://tiennm99.github.io">miti99</a> with ❤️ using <a href="https://www.mkdocs.org/" target="_blank">MkDocs</a> & <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank">Material for MkDocs</a><br>
  Copyright &copy; 2024 Tiên Thiếu Sắc. License:
  <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license">CC BY 4.0</a><br>
repo_url: https://github.com/tienthieusac/tienthieusac.github.io
repo_name: tienthieusac.github.io