[build]
  command = """
    curl https://pyenv.run | bash

    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init --path)"

    pyenv install 3.12.2
    pyenv global 3.12.2

    python3.12 -m venv venv
    source venv/bin/activate

    python -m pip install -r requirements.txt

    mkdocs build
  """

  publish = "site"